version: '3'

services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - devops-project_sonarqube_data:/opt/sonarqube/data
      - devops-project_sonarqube_logs:/opt/sonarqube/logs

volumes:
  devops-project_sonarqube_data:
    external: true
  devops-project_sonarqube_logs:
    external: true
version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: expensetracker_db
      POSTGRES_USER: tlad
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      SQL_HOST: db  # Explicitly set service name
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

