version: '3'

services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - devops-project_sonarqube_data:/opt/sonarqube/data
      - devops-project_sonarqube_logs:/opt/sonarqube/logs

volumes:
  devops-project_sonarqube_data:
    external: true
  devops-project_sonarqube_logs:
    external: true

