apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensetracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expensetracker
  template:
    metadata:
      labels:
        app: expensetracker
    spec:
      containers:
        - name: expensetracker
          image: tlad1/expensetracker:latest
          ports:
            - containerPort: 8000
          env:
            - name: SQL_HOST
              value: postgres

