apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: expensetracker_db
            - name: POSTGRES_USER
              value: tlad
            - name: POSTGRES_PASSWORD
              value: "123"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              memory: "4Gi"
              cpu: "2000m"    # 2 vCPUs
            requests:
              memory: "2Gi"
              cpu: "1000m"    # 1 vCPU
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

